server:
  port: 8082

spring:
  application:
    name: scraping
  datasource:
    url: jdbc:mysql://localhost:3306/projecthermesdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0