server:
  port: 8080

spring:
  application:
    name: article

  data:
    mongodb:
      uri: ${MONGO_DB_URI}

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    article: article.queue
  routing-keys:
    internal-article: internal.article.routing-key
