server:
  port: 8761

spring:
  application:
    name: eureka-server

  data:
    mongodb:
      uri: ${MONGO_DB_URI}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  tracing:
    sampling:
      probability: 1.0