server:
  port: 8083

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: article
          uri: lb://ARTICLE
          predicates:
            - Path=/api/articles/**
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/users/**
        - id: scraping
          uri: lb://SCRAPING
          predicates:
            - Path=/api/scraping/**
        - id: elasticsearch
          uri: lb://ELASTICSEARCH
          predicates:
            - Path=/api/elastic/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://localhost:*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers: "*"
            allow-credentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0