server:
  port: 8082

spring:
  application:
    name: scraping

  data:
    mongodb:
      uri: ${MONGO_DB_URI}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    elastic-saver: elastic-saver.queue
  routing-keys:
    internal-elastic-saver: internal.elastic-saver.routing-key